<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFrVKgw\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFrVKgw/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIFrVKgw.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIFrVKgw\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIFrVKgw\appAppKernelProdContainer([
    'container.build_hash' => 'IFrVKgw',
    'container.build_id' => 'b9de28fb',
    'container.build_time' => 1712329893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFrVKgw');
