<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCCSbHmr\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCCSbHmr/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerCCSbHmr.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerCCSbHmr\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerCCSbHmr\appAppKernelProdContainer([
    'container.build_hash' => 'CCSbHmr',
    'container.build_id' => '8e90ccb8',
    'container.build_time' => 1712951747,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCCSbHmr');
