<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLtuqFD8\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLtuqFD8/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLtuqFD8.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLtuqFD8\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLtuqFD8\appAppKernelProdContainer([
    'container.build_hash' => 'LtuqFD8',
    'container.build_id' => 'fd3d7953',
    'container.build_time' => 1712170515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLtuqFD8');
