<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR2gSxbc\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR2gSxbc/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerR2gSxbc.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerR2gSxbc\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerR2gSxbc\appAppKernelProdContainer([
    'container.build_hash' => 'R2gSxbc',
    'container.build_id' => '7122e372',
    'container.build_time' => 1712330282,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR2gSxbc');
